#!/bin/bash
# Chromium wrapper used as W2A_CHROME_PATH. Tuned hard for a 512MB container:
# shared single renderer + small V8 heap + no site isolation processes.
exec /usr/bin/chromium \
  --no-sandbox \
  --disable-dev-shm-usage \
  --disable-gpu \
  --window-size=800,600 \
  --lang=en-US \
  --renderer-process-limit=1 \
  --process-per-site \
  --disable-site-isolation-trials \
  --js-flags="--max-old-space-size=96 --max-semi-space-size=16" \
  --disk-cache-size=16777216 \
  --disable-features=Translate,BackForwardCache,HeavyAdIntervention,IsolateOrigins,site-per-process,CalculateNativeWinOcclusion \
  --disable-background-timer-throttling \
  --disable-backgrounding-occluded-windows \
  --disable-renderer-backgrounding \
  --disable-component-update \
  --mute-audio \
  "$@"
